services:
  kafka:
    image: apache/kafka:latest
    container_name: innomine-kafka
    ports:
      - "9092:9092" # host access: localhost:9092
    environment:
      # Official Apache Kafka image (KRaft combined mode, single node)
      # External clients (your Python code) connect via localhost:9092
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093

      # Single-broker dev defaults
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0

  postgres:
    image: postgres:16-alpine3.23
    container_name: innomine-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=innomine
      - POSTGRES_USER=innomine
      - POSTGRES_PASSWORD=innomine
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
